### ISSUE TITLE
FeatureLayers overlaying CircleMarkers

### ISSUE THREAD

**Issue by steveputman** [bhaskarvk/leaflet.esri#2]
Bhaskar,

I'm not sure if this is a leaflet.esri issue, a generic leaflet issue, or a user issue, but I'm having trouble getting circleMarkers added in a leaflet map to show up on top of esri FeatureLayers.  Some example code is below (where I have left the stroke on the congressional district polygons intentionally heavy to show how the circleMarkers are obscured by the FeatureLayers). 

Seems like it would be solved if you were able to set high z-index for circleMarkers, but I have been unable to find any good documentation on that, and I am not even clear that that's something we can fiddle with until the R leaflet package calls Leaflet >=1.0.

Thanks, as always, for the help.

Steve

```
library(leaflet)
library(leaflet.esri)


cities <- read.csv(textConnection("
City,Lat,Long,Pop
Boston,42.3601,-71.0589,645966
Hartford,41.7627,-72.6743,125017
New York City,40.7127,-74.0059,8406000
Philadelphia,39.9500,-75.1667,1553000
Pittsburgh,40.4397,-79.9764,305841
Providence,41.8236,-71.4222,177994
"))

leaflet(cities) %>%
  addEsriBasemapLayer("Gray") %>%
  addEsriFeatureLayer(url = "https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Congressional_Districts/FeatureServer/0", 
                      color = "blue") %>%
  addCircleMarkers(color = "red",
                   stroke = FALSE,
                   radius = 5,
                   fillOpacity = 1)
```

**Comment by bhaskarvk** [comment]
Thanks! I will check it out.

**Comment by steveputman** [comment]
I think this is fixed (or at least can be messed with) with change to Leaflet version.
